# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p3110/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/p31xx/common/system/bin/dock_kbd_attach:system/bin/dock_kbd_attach \
    vendor/samsung/p31xx/common/system/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/p31xx/common/system/bin/gpsd:system/bin/gpsd \
    vendor/samsung/p31xx/common/system/bin/orientationd:system/bin/orientationd \
    vendor/samsung/p31xx/common/system/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/p31xx/common/system/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/p31xx/common/system/etc/wifi/bcmdhd_p2p.bin:system/etc/wifi/bcmdhd_p2p.bin \
    vendor/samsung/p31xx/common/system/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/p31xx/common/system/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/p31xx/common/system/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/p31xx/common/system/lib/hw/vendor-camera.piranha.so:system/lib/hw/vendor-camera.piranha.so \
    vendor/samsung/p31xx/common/system/lib/hw/gps.omap4.so:system/lib/hw/gps.omap4.so \
    vendor/samsung/p31xx/common/system/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so:system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so:system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so \
    vendor/samsung/p31xx/common/system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so \
    vendor/samsung/p31xx/common/system/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
    vendor/samsung/p31xx/common/system/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/p31xx/common/system/lib/libdomx.so:system/lib/libdomx.so \
    vendor/samsung/p31xx/common/system/lib/libion.so:system/lib/libion.so \
    vendor/samsung/p31xx/common/system/lib/libmm_osal.so:system/lib/libmm_osal.so \
    vendor/samsung/p31xx/common/system/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/p31xx/common/system/lib/libtiutils.so:system/lib/libtiutils.so \
    vendor/samsung/p31xx/common/system/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/samsung/p31xx/common/system/vendor/firmware/BCM4330.hcd:system/vendor/firmware/BCM4330.hcd \
    vendor/samsung/p31xx/common/system/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/samsung/p31xx/common/system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/samsung/p31xx/common/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/samsung/p31xx/common/system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/samsung/p31xx/common/system/vendor/lib/hw/gralloc.omap4.so:system/vendor/lib/hw/gralloc.omap4.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/p31xx/common/system/vendor/lib/libusc.so:system/vendor/lib/libusc.so
